// api/note.js
// GET /api/note?studentId=A001&module=self&day=3
// GET /api/note?studentId=A001&module=self&day=3&audience=coach   (coach path)
// Per docs/v5-spec/engineering/07-pr4c §3-D.
//
// Response shape:
//   { day, noteText, exists }   (+ audience: 'coach' when applicable)
//
// ⚠️ B1 fix (PR-4c-4d):
//   STUDENT path (default audience='student'): returns sessions.notebook_page —
//     the Vivi-warm version generated by generateNotebookPage. NEVER returns the
//     coach-internal Damon Note fullNote (which contains 【SC 觀察】 / 【深度層次】 /
//     【採集追蹤】 / 工具一-四 / Layer 1-5 — coach analysis only).
//   The result is also passed through sanitizeStudentNote() defense-in-depth —
//     if Sonnet ever drifts and leaks coach internals into notebook_page, the
//     scrubber strips them at the API boundary.
//
//   COACH path (audience='coach'): returns damon_notes.note_text — the fullNote
//     with all coach-internal sections.
//     PR-4c-green Patrick 5/24 follow-up — gated behind guardCoachOr401
//     (getToken + COACH_EMAIL). 401 if no coach session. PR-4c-5 debt cleared.

import { neon } from '@neondatabase/serverless';
import { sanitizeStudentNote, containsForbiddenContent } from '../lib/api/student-note-safe.js';
import { guardCoachOr401 } from '../lib/auth/coach-session.js';

export const maxDuration = 10;

export default async function handler(req, res) {
  if (req.method !== 'GET') return res.status(405).json({ error: 'Method not allowed' });
  const studentId = String(req.query?.studentId || '').trim();
  const module    = String(req.query?.module    || 'self').trim();
  const day       = parseInt(req.query?.day);
  const audience  = String(req.query?.audience  || 'student').toLowerCase();
  if (!studentId) return res.status(400).json({ error: 'Missing required query: studentId' });
  if (!Number.isFinite(day) || day < 1 || day > 21) {
    return res.status(400).json({ error: 'Invalid day (1-21)' });
  }

  const sql = neon(process.env.DATABASE_URL);

  try {
    if (audience === 'coach') {
      // PR-4c-green Patrick 5/24 — gate the coach-internal branch behind
      // getToken + COACH_EMAIL. Student-default path stays open (above this).
      if (!(await guardCoachOr401(req, res))) return;
      // Coach path — return fullNote (coach-internal sections included).
      // Keyed by (student_id, module, week=ceil(day/7), day, is_week_summary=false).
      const week = Math.ceil(day / 7);
      const rows = await sql`
        SELECT note_text FROM damon_notes
        WHERE student_id = ${studentId} AND module = ${module}
          AND week = ${week} AND day = ${day}
          AND is_week_summary = FALSE
        LIMIT 1
      `;
      if (rows.length === 0) {
        return res.status(200).json({ day, noteText: null, exists: false, audience: 'coach' });
      }
      return res.status(200).json({
        day, noteText: rows[0].note_text, exists: true, audience: 'coach',
      });
    }

    // STUDENT path — sessions.notebook_page (Vivi-warm) + sanitize.
    // The Nth chronological session = the journey's Nth day (matches the cell index).
    const rows = await sql`
      SELECT notebook_page FROM sessions
      WHERE student_id = ${studentId} AND module = ${module}
        AND notebook_page IS NOT NULL
      ORDER BY session_date ASC
      LIMIT 1 OFFSET ${day - 1}
    `;
    if (rows.length === 0 || !rows[0].notebook_page) {
      return res.status(200).json({ day, noteText: null, exists: false });
    }
    const raw = rows[0].notebook_page;
    if (containsForbiddenContent(raw)) {
      // Observability: log loudly so a drifted Sonnet output surfaces in ops.
      console.warn(`[note B1] notebook_page for ${studentId} day=${day} contained forbidden coach-internal content — sanitized at API boundary`);
    }
    return res.status(200).json({
      day, noteText: sanitizeStudentNote(raw), exists: true,
    });
  } catch (e) {
    console.error('[note] error:', e);
    return res.status(500).json({ error: 'Server error' });
  }
}
